sources:
  - name: raw
    database: gold-north-america
    schema: gold_north_america
    tables:
      - name: results
      - name: goalscorers
      - name: shootouts
      - name: former_names
      - name: fifa_rankings
      - name: squad_quality
      - name: predictions_group_stage
      - name: predictions_knockout
      - name: actual_results
